services:
  mongodb:
    image: mongo
    networks:
      - lemoncode-challenge
    ports:
      - 27017:27017
    volumes:
      - mongo-volmongo:/data/db

  backend:
    build: ./backend/backend
    networks:
      - lemoncode-challenge
    ports:
      - 5000:5000
    environment:
      - MONGO_URI=mongodb://mongodb:27017

  frontend:
    build: ./frontend
    networks:
      - lemoncode-challenge
    ports:
      - 3000:3000
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api/topics

networks:
  lemoncode-challenge:
    driver: bridge

volumes:
  mongo-volmongo:
